---
apiVersion: v2
name: webstore-demo-gitops
type: application
version: 0.1.2
appVersion: "0.4.8"
dependencies:
- name: opentelemetry-demo
  version: 0.4.9
  repository: https://openinsight-proj.github.io/openinsight-helm-charts
  condition: opentelemetry-demo.enabled
