global:
  autoInstrumentation:
    enabled: true
    config:
      apiVersion: opentelemetry.io/v1alpha1
      kind: Instrumentation
      metadata:
        name: opentelemetry-autoinstrumentation-webstore-demo
      spec:
        # https://github.com/open-telemetry/opentelemetry-operator/blob/main/docs/api.md#instrumentationspecresource
        resource:
          addK8sUIDAttributes: true
        sampler:
          # Enum: always_on, always_off, traceidratio, parentbased_always_on, parentbased_always_off, parentbased_traceidratio, jaeger_remote, xray
          type: always_on
        java:
          image: ghcr.m.daocloud.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:1.17.0
          env:
            - name: OTEL_JAVAAGENT_DEBUG
              value: "false"
            - name: OTEL_INSTRUMENTATION_JDBC_ENABLED
              value: "true"
            - name: SPLUNK_PROFILER_ENABLED
              value: "false"
        nodejs:
          image: ghcr.m.daocloud.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:0.31.0
        python:
          image: ghcr.m.daocloud.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python::0.33b0
  serviceMonitor:
    adservice:
      enabled: false

opentelemetry-demo:
  enabled: true

  opentelemetry-demo:
    components:
      adService:
        enabled: false